version: '1'
services:
  redis:
    image: redis:alpine
    command: [ "redis-server", "--bind", "127.0.0.1" ]
    environment:
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis-10890.c311.eu-central-1-1.ec2.cloud.redislabs.com:10890
#    ports:
#      - "6379:6379"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data